version: '3.8'

services:
  db:
    container_name: mysql
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: globits
    volumes:
      - mysql_data_globis:/var/lib/mysql
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin:latest
    restart: always
    ports:
      - "8888:80"
    environment:
      PMA_ARBITRARY: 1


volumes:
  mysql_data_globis: